server:
  port: "8081"
  mode: "debug" # debug, release, test

database:
  mysql:
    # Example:
    # dsn: "root:password@tcp(127.0.0.1:3306)/uni-search-hub?charset=utf8mb4&parseTime=True&loc=Local"
    dsn: ""
  redis:
    # Set addr to "" to disable Redis.
    addr: "127.0.0.1:6380"
    password: ""

